snoopee-discovery/snoopee-service/src/main/java/eu/agilejava/snoopee/ui/SnoopController.java
/*
 * The MIT License
 *
 * Copyright 2015 Ivar Grimstad (ivar.grimstad@gmail.com).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package eu.agilejava.snoopee.ui;

import eu.agilejava.snoopee.SnoopEEClientRegistry;
import eu.agilejava.snoopee.SnoopEEConfig;
import java.util.Collection;
import java.util.Set;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 * Controller for the SnoopEE service UI.
 * 
 * @author Ivar Grimstad (ivar.grimstad@gmail.com)
 */
@Named
@RequestScoped
public class SnoopController {

   private static final Logger LOGGER = Logger.getLogger("eu.agilejava.snoopee");

   @EJB
   private SnoopEEClientRegistry clients;

   public Set<String> getClients() {
      return clients.getClients();
   }
   
   public Collection<SnoopEEConfig> getClientConfigurations() {
      return clients.getServiceConfigs();
   }
}

snoopee-discovery/snoopee-service/src/main/webapp/WEB-INF/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <ui:param name="root" value="#{request.contextPath}/"/>
        <h:outputStylesheet name="css/default.css"/>
        <h:outputStylesheet name="css/cssLayout.css"/>
        <link rel="shortcut icon" href="#{root}resources/images/favicon.ico" type="image/x-icon"/>
        <link rel="icon" href="#{root}resources/images/favicon.ico" type="image/x-icon"/>
        <title>SnoopEE Discovery Service</title>
    </h:head>

    <h:body>

        <div id="top">
            <ui:insert name="top">
                <h1>Welcome to SnoopEE Discovery Service</h1>
            </ui:insert>
        </div>

        <div id="content" class="center_content">
            <ui:insert name="content">Content</ui:insert>
        </div>

        <div id="bottom">
            <ui:insert name="bottom">
                <h:outputLink value="https://twitter.com/ivar_grimstad" target="_blank">@ivar_grimstad</h:outputLink><br />
                Licensed under the MIT License.
            </ui:insert>
        </div>


    </h:body>

</html>

snoopee-discovery/snoopee-service/src/main/webapp/services.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

   <h:body>

      <ui:composition template="./WEB-INF/template.xhtml">

         <ui:define name="content">

            <h2>Registered Services</h2>
            <h:form>
               <h:dataTable value="${snoopController.clientConfigurations}" var="client">

                  <h:column>
                     <f:facet name="header">
                        <h:outputText value="Service Name"/>
                     </f:facet>
                     <h:outputText value="#{client.serviceName}"/>
                  </h:column>

                  <h:column>
                     <f:facet name="header">
                        <h:outputText value="Service Home"/>
                     </f:facet>
                     <h:outputLink target="_blank" value="#{client.serviceHome}#{client.serviceRoot}">#{client.serviceHome}#{client.serviceRoot}</h:outputLink>
                  </h:column>

               </h:dataTable>
            </h:form>
         </ui:define>

      </ui:composition>

   </h:body>
</html>